apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mjir-qwk9-python 
  janus-idp.io/tekton: mjir-qwk9-python
  backstage.io/kubernetes-id: mjir-qwk9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mjir-qwk9-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  